### ISSUE TITLE
copy: object validator callback

### ISSUE THREAD

**Issue by yhahn** [mapbox/tilelive#130]
Goals for doing object-level validation during copies:

- let's make it unspecific to which stream type, source type, copy operation type is being used
- let's make the actual validation unbolted to tilelive
- let's make it validate as processing occurs

------

- [ ] Sketch addition of object validation callback to tilelive.js. It will need to be async (?)
- [ ] Break up + port validations in https://github.com/mapbox/mapbox-upload-validate/blob/master/lib/validators/serialtiles.js#L16 against branch

cc @rclark @tmcw

**Comment by yhahn** [comment]
Per convo with @tmcw, given that various implementations are not using `tilelive.copy` directly but just streaming various pipes into each other...

- Should we implement this object validator as a stream you can pipe into (like https://github.com/freeall/progress-stream)
- Optionally pass intermediate pipe streams to tilelive-copy?

We would then include this validator in the copy pipes of mapbox-studio, mapbox-tile-copy etc.

cc @tmcw @rclark

**Comment by rclark** [comment]
Yeah, either tilelive lets you drop in a transform stream, or tilelive lets you define essentially the `_transform` function and puts the stream into the pipeline itself. 

Flexibility vs. simplicity. My moral compass is happy either way.

**Comment by yhahn** [comment]
Donezo
