### ISSUE TITLE
tilelive.copy is undocumented

### ISSUE THREAD

**Issue by tmcw** [mapbox/tilelive#138]

**Comment by springmeyer** [comment]
The command line interface (https://github.com/mapbox/tilelive.js/blob/master/bin/tilelive-copy) could also really benefit from better error handling/reporting. Wondering about coverage as a first step I've noticed:
 
   - tilelive.js does have coverage/coveralls enabled (https://coveralls.io/github/mapbox/tilelive.js)
   - but only the lib/ directory is being reported on
   - I wondered if the `--include-all-sources` flag to istanbul might be the problem (https://github.com/gotwarlost/istanbul/pull/275)
   - But, no it just looks like istanbul is not being ask to cover the bin/ folder and of course its questionable how that would work.
   - So perhaps we just need tape tests to shell out to tilelive-copy to be able to cover it?

**Comment by yhahn** [comment]
> So perhaps we just need tape tests to shell out to tilelive-copy to be able to cover it?

https://github.com/mapbox/tilelive.js/blob/master/test/copy.test.js#L18-L97

The tape tests do shell out, though I doubt coveralls covers child processes that way...

**Comment by tmcw** [comment]
[nyc](https://www.npmjs.com/package/nyc) can cover subprocesses, not sure if it's just child_process or exec though
