### ISSUE TITLE
de/serialize: round-trip test sometimes fails

### ISSUE THREAD

**Issue by tomhughes** [mapbox/tilelive#152]
It's not consistent, but the I've seen the "de/serialize: round-trip" test in stream-deserialize.test.js fail several times:

```
# de/serialize: round-trip
ok 216 null
not ok 217 round-tripped mbtiles are approx. the same size
  ---
    operator: ok
    expected: true
    actual:   false
    at: Put.makeAssertions (/builddir/build/BUILD/tilelive-5.11.0/test/stream-deserialize.test.js:189:11)
  ...
```

I assume the threshold is maybe a bit too tight and, depending on environmental details, it may be exceeded?

**Comment by mapsam** [comment]
I've noticed this as well recently - especially with node v0.12.x and v5. Will take a look.

**Comment by mapsam** [comment]
I'm never able to recreate this error on mac, but it happens regularly on linux. I've logged the diff for node 0.10, 4, and 6:

0.10: `0.011764705882352941`   
4: `0.023391812865497075` and `0.011834319526627219`
6: `0.023121387283236993`

It appears unrelated to versions. I'm in favor of increasing the threshold here to something a bit more flexible - not sure why `0.1` was chosen in the first place though. 

cc @rclark

**Comment by rclark** [comment]
We can certainly adjust this threshold. A better test would be one that actually asserts that the tile data itself successfully navigates the roundtrip through serialization.

**Comment by mapsam** [comment]
I've rewritten this test to `deepEqual` on the `getInfo` object for the input mbtiles and the output mbtiles here: 303f05535b64a806e746ed0622290df13cfe6d9a

**Comment by mapsam** [comment]
This test has been rewritten and is now part of version `5.12.5` #195
