### ISSUE TITLE
Updating source

### ISSUE THREAD

**Issue by divya1c** [mapbox/tilelive#163]
Hi!

I want to update my mbtiles source every 10 minutes. Is it possible to reload or switch sources in tilelive? Or is there any other way I can go about this? 

Thanks!

**Comment by wandergis** [comment]
I also want to konw how to reload. I use tilelive with node express ,when i change the mapnik xml file,i must restart my server. Does it can do like mapbox studio when change the style and save then the map can reload with the new style?

**Comment by divya1c** [comment]
I am not sure if mapnik xml files are operated the same way. I was able to successfully reload mbtiles by calling tilelive.load and switching sources in node. Hope that helps :)

**Comment by wandergis** [comment]
Can you give some sample code ? Thks very much.
