### ISSUE TITLE
The ecosystem of tilelive

### ISSUE THREAD

**Issue by jingsam** [mapbox/tilelive#175]
I find it is rather confusion on what does each tilelive modules do and how they are connected. So I summarized all pieces as bellow. Any suggestions?

![image](https://cloud.githubusercontent.com/assets/1522494/16645056/a8f8fff2-4453-11e6-8ba7-b9aff033f2cd.png)

**Comment by rclark** [comment]
This is great! Would you like to include this in tilelive's readme? Do you have any other suggestions about how the readme could do better to clarify the state of the tilelive ecosystem?

**Comment by jingsam** [comment]
Send a PR https://github.com/mapbox/tilelive/pull/176

**Comment by mapsam** [comment]
This is in the readme, thanks again!
