### ISSUE TITLE
What is tilelive?

### ISSUE THREAD

**Issue by mg262** [mapbox/tilelive#183]
The documentation for this project is a bit confusing: 

>Tilelive is a module to help interactions between tilelive source modules.

I don't know what the tilelive source modules do.  As far as I can see, this is the front page for the whole tilelive project. It would be nice to have a sentence or two explaining what the purpose/scope of this project is...

**Comment by mapsam** [comment]
@mg262 this is a great question, apologies for the delayed response. I've drafted up a bit of prose that can be added to the README after review here: https://github.com/mapbox/tilelive/pull/197

**Comment by mapsam** [comment]
Answered in https://github.com/mapbox/tilelive/pull/197
