### ISSUE TITLE
Is this still being actively maintained?

### ISSUE THREAD

**Issue by guyisra** [mapbox/tilelive#211]
In almost the past year this had only documentation fixes and no code changes

Should this have more maintainers? or has Mapbox abandoned this project?

**Comment by guyisra** [comment]
@mapsam @yhahn @nyurik ^^^ ?

**Comment by mapsam** [comment]
@guyisra 👋 sorry for the delay! We're a bit limited for resources on our end, so this library hasn't gotten the attention it deserves. Subsequently, we aren't _actively_ maintaining this right now, but it is certainly still be used internally and externally. 

For now, I'm going to add a note in the README saying we are not actively maintaining tilelive and downstream mapbox-owned tilelive plugins, except for any security-related bug fixes.
