### ISSUE TITLE
tilelive-copy simplification?

### ISSUE THREAD

**Issue by georgbachmann** [mapbox/tilelive#212]
I have a project setup in MapboxStudio Classic and I am trying to export my dataset as vector (using `generate-vectortiles` which uses tilelive-copy).

When I zoom in quite far in MapboxStudio, my lines are nice and smooth. I only export my tiles to zoom level 13 though, but on that zoom level, all my geometries have NO simplification any more. So I'd expect my tiles to already have all the information in them at zoom level 13 with smooth edges, right?
But now when I look at the final mbtiles and overzoom, my lines look as if they were simplificated?!?

Is there a setting to disable any kind of automatic simplification?

So for better understanding
This is how it looks in Mapbox Studio at zoom level 18:
<img width="684" alt="Screenshot 2019-04-05 at 17 22 56" src="https://user-images.githubusercontent.com/893113/55638867-7b95c780-57c8-11e9-8d45-e326409e2648.png">
(the one feature f.e. has 13 edges)

and the same road looks like this when exported and viewed in MapTiler:
<img width="750" alt="Screenshot 2019-04-05 at 17 23 05" src="https://user-images.githubusercontent.com/893113/55638874-805a7b80-57c8-11e9-85de-1d7693145eab.png">
(the same feature here has only 8)

So... my postgres query for zoom level 13 does not do any simplification any more. So I'd expect the full vector information to be present at that scale and so I'd expect that overzooming should not be an issue. 

So I guess tilelive is going some simplification when exporting and I'd like to know if it's possible to disable that?

**Comment by golubev** [comment]
Hi, @georgbachmann! It seems to me that you are using openmaptiles. If so, the simplification you are talking about is being described for each layer in the corresponding yaml files (e.g. [mapping.yaml for the `landcover` layer](https://github.com/openmaptiles/openmaptiles/blob/dca81130d8b727d30fac0494b7dd476db3d2b613/layers/landcover/mapping.yaml#L2-L44)). It takes place not in the `tilelive`, but in the `imposm3`. See [their docs](https://imposm.org/docs/imposm3/latest/mapping.html#generalized-tables).

It looks to me that this is not an issue with the tilelive.
